{{- range .Values.nfsserver.exports }}
{{- $pvc := .persistentVolumeClaim }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    app: rook-nfs
  name: {{ .nfsStorageClassName }}
parameters:
  exportName: {{ .name }}
  nfsServerName: {{ $.Values.nfsserver.name }}
  nfsServerNamespace: {{ $.Values.nfsserver.name }}
provisioner: nfs.rook.io/rook-nfs-provisioner
reclaimPolicy: Delete
volumeBindingMode: Immediate
{{- end }}