apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "storage-nvme-rook-nfs.operator.serviceAccountName" . }}
  labels:
    {{- include "storage-nvme-rook-nfs.labels" . | nindent 4 }}
  {{- with .Values.operator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Values.operator.namespace }} # namespace:operator