{{- if and .Values.serviceAccount.create (not .Values.kubeconfigSecret.name) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubeflow-installer.fullname" . }}
  labels: {{ include "kubeflow-installer.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ tpl .Values.serviceAccount.name . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.serviceAccount.clusterRoleName }}
{{- end }}
