{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubeflow-installer.fullname" . }}-manage-jobs
  labels: {{ include "kubeflow-installer.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ tpl .Values.serviceAccount.name . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubeflow-installer.fullname" . }}-manage-jobs
{{- end }}
