{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ tpl .Values.serviceAccount.name . }}
  labels: {{ include "kubeflow-installer.labels" . | nindent 4 }}
{{- end }}
