apiVersion: nfs.rook.io/v1alpha1
kind: NFSServer
metadata:
  name: {{ .Values.nfsserver.name }}
  namespace: {{ .Values.nfsserver.namespace }}
  labels:
    app: rook-nfs
    {{- include "storage-ceph-rook-nfs.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.nfsserver.replicaCount }}
  exports:
    {{- range .Values.nfsserver.exports }}
    - name: {{ .name }}
      server:
        accessMode: {{ .server.accessMode }}
        squash: {{ .server.squash | quote }}
      persistentVolumeClaim:
        claimName: {{ .persistentVolumeClaim.claimName }}
    {{- end }}
  # A key/value list of annotations
{{- with .Values.podAnnotations }}
  annotations:
    rook: nfs
    {{- toYaml . | nindent 4 }}
{{- end }}
    