apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-nfs-server
  labels:
    {{- include "storage-ceph-rook-nfs.labels" . | nindent 4 }}
  {{- with .Values.nfsserver.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Values.nfsserver.namespace }} # namespace:nfsserver