apiVersion: v2
name: jupyterhub-zenith
description: A Helm chart for a Zenith-integrated JupyterHub
type: application
version: 0.1.0

dependencies:
  - name: jupyterhub
    version: 1.2.0
    repository: https://jupyterhub.github.io/helm-chart/
